# Generated by Django 2.2 on 2019-04-19 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0005_remove_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
