# Generated by Django 2.2 on 2019-04-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0007_auto_20190419_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
